"""Items, Period, Plan

Revision ID: ca6d24919f07
Revises: b4eb34fd2d1a
Create Date: 2026-10-06 23:01:13.539422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6d24919f07'
down_revision: Union[str, Sequence[str], None] = 'b4eb34fd2d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('stop_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('measure_unit_id', sa.Integer(), nullable=False),
    sa.Column('preferred_unit_id', sa.Integer(), nullable=False),
    sa.Column('transform_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['measure_unit_id'], ['measure_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_unit_id'], ['measure_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    op.drop_table('item')
    op.drop_table('period')
    # ### end Alembic commands ###
