"""createDateMixin, Branch, FileStorage

Revision ID: b4eb34fd2d1a
Revises: 8f40595ef740
Create Date: 2026-10-06 21:40:45.018219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4eb34fd2d1a'
down_revision: Union[str, Sequence[str], None] = '8f40595ef740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_store',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('measure_unit', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measure_unit', 'create_date')
    op.drop_table('file_store')
    op.drop_table('branch')
    # ### end Alembic commands ###
