"""fix Category

Revision ID: f6ebaefb7d5a
Revises: e0d8c2e7e401
Create Date: 2026-10-07 13:46:49.199701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ebaefb7d5a'
down_revision: Union[str, Sequence[str], None] = 'e0d8c2e7e401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('path', sa.String(length=1024), nullable=False))
    op.create_index(op.f('ix_category_path'), 'category', ['path'], unique=False)
    op.drop_constraint(op.f('category_parent_id_fkey'), 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('category_parent_id_fkey'), 'category', 'category', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_category_path'), table_name='category')
    op.drop_column('category', 'path')
    # ### end Alembic commands ###
